stages:
  preprocess:
    # Run the data preprocessing script
    cmd: python -m ExampleML2.preprocess_dataset ExampleML2/config/params.yaml ExampleML2/data-raw/weather.csv ExampleML2/data-processed/weather.csv
    deps:
    - ExampleML2/preprocess_dataset.py
    - ExampleML2/data-raw/weather.csv
    - ExampleML2/utils_and_constants.py
    params:
      - ExampleML2\config\params.yaml:
        - preprocess
    outs:
    - ExampleML2/data-processed/weather.csv
  train_and_evaluate:
    # Run the model training and evaluation script
    cmd: python -m ExampleML2.train_and_evaluate ExampleML2/config/params.yaml ExampleML2/data-processed/weather.csv
    deps:
    - ExampleML2/metrics_and_plots.py
    - ExampleML2/model.py
    # Specify the preprocessed dataset as a dependency
    - ExampleML2/data-processed/weather.csv
    - ExampleML2/train_and_evaluate.py
    - ExampleML2/utils_and_constants.py
    params:
      - ExampleML2\config\params.yaml:
        - train_and_evaluate
    outs:
    - ExampleML2/images/confusion_matrix.png
    metrics:
    - ExampleML2/metrics/metrics.json:
        cache: false